# Generated by Django 5.2.3 on 2025-06-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_professors_delete_professor_rename_edat_alumne_curs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='curs',
            field=models.CharField(max_length=500),
        ),
    ]
